### ISSUE TITLE
Migrate to new site?

### ISSUE THREAD

**Issue by ldodds** [dodify/website-bathcarparks#2]
The Bath: Hacked data store is being migrated to a new platform, so the API will change.

While the `DATA_URL` in the code should work, the format of responses will change. This is likely to happen early next week. 

I'm not sure if people are still using this website, any idea of usage stats?

If so then it's would be great to update the code to use new URL/format. Can share if that's of interest

**Comment by mstremante** [comment]
I'd be happy to update - where can I find the new format docs?

**Comment by ldodds** [comment]
Theres a blog post about the new store here

https://www.bathhacked.org/news/previewing-our-new-datastore/


Theres a temporary domain until next week. Parking dataset is here

https://www.bhdata.co.uk/datasets/banes-live-car-park-occupancy

API is here

https://www.bhdata.co.uk/api/datasets/8/rows?page=1&per_page=15

**Comment by mstremante** [comment]
All fixed!
